### ISSUE TITLE
Button - can't use span class (Name) to adapt button font

### ISSUE THREAD

**Issue by cabutler10** [zepdev/zeppelin-element-library#111]
talk to @byjs-dev

**Comment by byjs-dev** [comment]
Sorry, I don't get the issue. :) Could you please provide some more info?

**Comment by cabutler10** [comment]
https://jira.zeppelin.com/browse/ZDS-475

**Comment by cabutler10** [comment]
@byjs-dev  ah i believe i got the stories mixed up, this appears to be a react bug that I need to fix...
