### ISSUE TITLE
ZEL.js number input and pagination examples fail

### ISSUE THREAD

**Issue by cabutler10** [zepdev/zeppelin-element-library#136]
ZEL.js number input and pagination examples fail

**Comment by byjs-dev** [comment]
Did you call ZEL.init() (or ZEL.refresh() after DOM manipulation)?

**Comment by byjs-dev** [comment]
I checked the code, the ZEL.refresh() call is missing. I'll add useLayoutEffect hook to App.js and do a PR. That will fix the NumberInputPage. And for Pagination we currently don't have any functionality in place - just styles. So I'll leave that as it is for the moment.
