### ISSUE TITLE
Color Themes - Guidelines SCSS 

### ISSUE THREAD

**Issue by byjs-dev** [zepdev/zeppelin-element-library#153]
* Remove all quotes(string) variables in map-deep-get() calls in $color_themes to make them work
* Check and update all vars in guideline.scss object.
    * e.g. map-deep-get($guidelines, theme, yellow, tertiary) -> tertiary does not exist!
* edit the whole the color assignment and make relevant rgba black/white opacity values (e.g. black.16, black.40, black.60, black.84 ...) accessible within themes

**Comment by cabutler10** [comment]
- to my knowledge scss will not let you re-name common color values like 'blue' so if we want our own blue we must mix string and non string values in guidelines. Does someone know another way or did you mean you want to rename our color values to be unique (ie 'zeppelinBlue').

- tertiary does and does not exist, UI/UX team was giving me mixed ideas if they wanted to keep the tertiary button then finally said they WOULD keep it and a design was coming soon, but that was 6 months ago now and my feeling is that they are no longer working on / sharing ideas for ZDS.  I kept it in zeppelin element library and it is currently an unstyled button. 

- what do you mean? it is accessible within the theme as theme.color.black[16].

**Comment by byjs-dev** [comment]
* Please ignore: Remove all quotes(string) variables in map-deep-get() calls in $color_themes to make them work -> this was not the issue. The issue is in the themify method. I don't get the expected output compared to a simple map-deep-get() call with the same params. I'll check that.
* we have to announce that in the next CoP Meeting
* i need it as theme.yellow.buttonText.84 -> button text color can be black or white depending on the theme color.

**Comment by sebbuku** [comment]
We added the base text colours for each theme according to the Abstract themes. The different levels of "lightness" can then be relatively easy calculated with SASS/CSS

**Comment by byjs-dev** [comment]
Recent changes should suffice. Using guidelines.json/guidelines.scss for specific colors outside of the color theme does the trick until we face a real issue or if we badly need a smarter way because of increasing complexity.
